#!/bin/sh /etc/rc.common

START=10
STOP=15

USE_PROCD=1

start_service() {
    procd_open_instance

    procd_set_param command /usr/bin/xbridge -2 -h br-lan -n enf0
    procd_set_param netdev "br-lan enf0"
    procd_set_param pidfile /var/run/xbridge.pid
    procd_set_param respawn "60 5 0"
    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_add_reload_interface_trigger "enf0"

    procd_close_instance
}

reload_service()
{
        stop
        start
}
